export const CREATE_ORDER = 'CREATE_ORDER';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const OFFER_ACTION = 'OFFER_ACTION';
export const GET_ORDERS = 'GET_ORDERS';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';
export const SET_MEETUP = 'SET_MEETUP';
export const ORDER_EXCHANGE = 'ORDER_EXCHANGE';
export const PAYMENT_DEFAULT = 'PAYMENT_DEFAULT';
export const GET_CARD_DETAIL = 'GET_CARD_DETAIL';
export const GET_COMPLETED_ORDER = 'GET_COMPLETED_ORDER';
export const SET_RETURN_ADDRESS = 'SET_RETURN_ADDRESS';
export const VALIDATE_ADDRESS = 'VALIDATE_ADDRESS';
export const GET_SHIPPING_LABEL = 'GET_SHIPPING_LABEL';
export const GET_PACKING_SLIP = 'GET_PACKING_SLIP';
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const GET_RETURN_REQUEST = 'GET_RETURN_REQUEST';
export const GET_RETURN_REASON = 'GET_RETURN_REASON';
export const RETURN_ORDER_UPDATE = 'RETURN_ORDER_UPDATE';
export const RETURN_REQUEST = 'RETURN_REQUEST';
export const CLAIM_REQUEST = 'CLAIM_REQUEST';
export const CHEAPEST_RATE = 'CHEAPEST_RATE';
export const SET_RETURN_LABEL = 'SET_RETURN_LABEL';
export const UPDATE_RETURN = 'UPDATE_RETURN';
export const SET_REFUND_AMOUNT = 'SET_REFUND_AMOUNT';
export const SET_INDEPENDENT_SHIPPING_CARRIER =
  'SET_INDEPENDENT_SHIPPING_CARRIER';
/* Store reducer key */
export const ORDER = 'order';
export const CANCEL_RETURN = 'CANCEL_RETURN';
export const CANCEL_CLAIM = 'CANCEL_CLAIM';
export const CLEAR_ORDER_ERROR = 'CLEAR_ORDER_ERROR';
export const ACCEPT_CANCELLATION = 'ACCEPT_CANCELLATION';
export const DENY_CANCELLATION = 'DENY_CANCELLATION';
export const RAISE_DISPUTE = 'RAISE_DISPUTE';



