-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgeFQtWldPmvNy3kns
oCFU+10IwGpo12OKgMtOrvUD2bGgCgYIKoZIzj0DAQehRANCAARBXDKjpUxou4+s
XOPZdjC9l4lnvbOfBy6bkiqGWeInpsYRae+3nGnd4zBuupGlrr/IZ0TWSs/crRIq
CDKneXwy
-----END PRIVATE KEY-----