import { StyleSheet, Platform } from "react-native";
import { Colors, Fonts, Metrics } from "#themes";
import colors from "#themes/colors";
import { isIphoneX } from "react-native-iphone-x-helper";

// eslint-disable-next-line import/prefer-default-export
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  header: {
    elevation: 3,
    backgroundColor: "#ffffff",
    alignItems: "center",
    paddingVertical: 15,
    flexDirection: "row",
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    elevation: 6,
    shadowRadius: 3,
    shadowOpacity: 0.3,
  },
  scrollContainer: {
    marginTop: 20,
  },
  verify_text: {
    fontFamily: Fonts.family.regular,
    fontSize: Fonts.size.h6,
    fontWeight: "700",
    color: Colors.black,
  },
  userId_icon: {
    width: 160,
    height: 100,
    alignSelf: "center",
    marginVertical: 30,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    elevation: 6,
    shadowRadius: 3,
    shadowOpacity: 0.25,
  },
  idVerification_text: {
    fontSize: Fonts.size.large,
    fontFamily: Fonts.family.regular,
    color: Colors.black,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 35,
  },
  idVerification_desc: {
    marginHorizontal: 30,
    fontSize: Fonts.size.large,
    fontFamily: Fonts.family.regular,
    color: Colors.black,
    fontWeight: "400",
    textAlign: "center",
  },
  select_ideidentification_text: {
    fontSize: Fonts.size.regular,
    fontFamily: Fonts.family.regular,
    color: Colors.black,
    fontWeight: "700",
    marginVertical: 25,
    marginLeft: 17,
  },
  ideidentification_background: {
    height: 45,
    width: "90%",
    justifyContent: "center",
    alignSelf: "center",
    backgroundColor: Colors.white,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    elevation: 6,
    shadowRadius: 3,
    shadowOpacity: 0.3,
    marginVertical: 15,
    borderRadius: 8,
  },
  radio_button: {
    height: 20,
    width: 20,
    borderWidth: 1,
    borderRadius: 20 / 2,
    marginHorizontal: 20,
  },
  userId_name: {
    fontSize: Fonts.size.regular,
    fontFamily: Fonts.family.regular,
    color: Colors.black,
    fontWeight: "700",
  },
  camera_allow_desc: {
    marginLeft: 17,
    fontSize: Fonts.size.regular,
    fontFamily: Fonts.family.regular,
    color: Colors.black,
    fontWeight: "400",
    marginRight: 20,
    marginBottom: 30,
  },
  photos_header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginHorizontal: 17,
    marginTop: 30,
    marginBottom: 40,
  },
  photos_header_text: {
    fontSize: Fonts.size.regular,
    fontFamily: Fonts.family.regular,
    color: Colors.black,
    fontWeight: "700",
  },
  userId_sample_image: {
    width: "80%",
    height: isIphoneX() ? 400 : 350,
    alignSelf: "center",
    marginVertical: 20,
  },
  action_view: {
    width: "100%",
    padding: 20,
    borderTopWidth: 0.7,
    borderBottomColor: "#efefef",
    borderTopColor: "#efefef",
  },
  dash_rectangle_image: {
    width: 375,
    height: 260,
    alignItems: "center",
    alignSelf: "center",
    marginVertical: 20,
    justifyContent: "center",
  },
  select_image_title: {
    fontSize: Fonts.size.regular,
    fontFamily: Fonts.family.regular,
    color: Colors.black,
    fontWeight: "700",
  },
  select_image_desc: {
    fontSize: Fonts.size.medium,
    fontFamily: Fonts.family.regular,
    color: Colors.black,
    fontWeight: "400",
    textAlign: "center",
    paddingHorizontal: 40,
    marginVertical: 20,
  },
  select_button: {
    width: 260,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.primary,
    borderRadius: 10,
  },
  cancel_button: {
    width: "90%",
    height: 50,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.primary,
    borderRadius: 10,
  },
  user_detail_box: {
    width: "90%",
    borderWidth: 1,
    borderRadius: 8,
    height: 230,
    alignSelf: "center",
    paddingHorizontal: 20,
    backgroundColor: Colors.lightGrey,
  },
  editIcon: {
    width: 25,
    height: 25,
    resizeMode: "contain",
  },
  agreement_text: {
    ...Fonts.style.label,
    marginRight: 10,
    marginLeft: 22,
    marginTop: 20,
    color: Colors.black,
    fontWeight: "400",
  },
  user_detail_text: {
    ...Fonts.style.instruction_Text,
    color: Colors.black,
    marginTop: 20,
  },
  camera_cancel_button: {
    padding: 16,
    backgroundColor: "white",
    shadowColor: "black",
    shadowOffset: { height: 0, width: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 54,
    elevation: 10,
    borderBottomWidth: 0,
  },
  //camera access modal style
  centeredView: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalView: {
    paddingVertical: 25,
    paddingHorizontal: 20,
    width: "85%",
    borderRadius: 5,
    height: 225,
    alignSelf: "center",
    backgroundColor: "white",
  },
  stripe_camera_text: {
    ...Fonts.style.homiBodyTextMedium,
    color: Colors.black,
    fontWeight: "400",
    paddingHorizontal: 10,
    marginBottom: 15,
  },
  loader_positon:{
    position: "absolute",
    zIndex: 1,
    bottom: 0,
    top: 0,
    left: 0,
    right: 0,
  }
});
