import { ORDER_STATUS } from "#utils/enums";

export const tabs = [
  {
    name: "All",
    id: 0,
    statuses: [],
  },
  {
    name: "Buying",
    id: 1,
    statuses: ["buying", ORDER_STATUS.PENDING, ORDER_STATUS.CREATED],
    options: ["View Order Status", "Help", "Cancel"],
  },
  {
    name: "Bought",
    id: 2,
    statuses: [
      "bought",
      "soldout",
      "shipped",
      "cancellation_cancelled",
      ORDER_STATUS.ACCEPTED,
      ORDER_STATUS.DELIVERED,
      ORDER_STATUS.AWAITING_SHIPPING,
      ORDER_STATUS.CANCELLATION_DENIED,
      ORDER_STATUS.CLAIM_DENIED,
      "full_refund",
      "partial_refund",
      "partial_shipped",
      "buyer_funded_claim",
      "seller_funded_claim",
      "homitag_funded_claim",
      ORDER_STATUS.RETURN_CANCELLED,
    ],
    options: [
      "Message Seller",
      "View Order Status",
      "Share Item",
      "Help",
      "Cancel",
    ],
  },
  {
    name: "Return/Cancellation",
    id: 3,
    statuses: [
      ORDER_STATUS.INACTIVE,
      ORDER_STATUS.RETURN_ACCEPTED,
      ORDER_STATUS.RETURN_CLOSED,
      ORDER_STATUS.RETURN_COMPLETED,
      ORDER_STATUS.RETURN_REQUESTED,
      ORDER_STATUS.RETURN_SHIPPED,
      ORDER_STATUS.CANCELLATION_REQUESTED,
      ORDER_STATUS.CANCELLED,
      ORDER_STATUS.CLAIM_ACCEPTED,
      ORDER_STATUS.CLAIM_CLOSED,
      ORDER_STATUS.CLAIM_DISPUTED,
      ORDER_STATUS.CLAIM_FILED,
      ORDER_STATUS.RETURN_DENIED,
    ],
    options: [
      "Message Seller",
      "View Order Status",
      "Share Item",
      "Help",
      "Cancel",
    ],
  },
];
