import { ORDER_STATUS } from '#utils/enums';

export const tabs = [
  {
    name: 'All',
    id: 0,
    statuses: [],
    options: [
      'Message Buyer',
      'View Order Status',
      'Share Item',
      'Help',
      'Cancel',
    ],
  },
  {
    name: 'Listed',
    id: 1,
    statuses: ['buying', 'active', 'inactive', 'draft'],
    options: ['Edit Listing', 'Help', 'Cancel'],
  },
  {
    name: 'Pending',
    id: 2,
    statuses: [],
    options: ['View Order Status', 'Help', 'Cancel'],
  },
  {
    name: 'Orders',
    id: 3,
    statuses: [
      'bought',
      'soldout',
      'shipped',
      'cancellation_cancelled',
      'inactive (sold out)',
      ORDER_STATUS.ACCEPTED,
      ORDER_STATUS.DELIVERED,
      ORDER_STATUS.AWAITING_SHIPPING,
      ORDER_STATUS.CANCELLATION_DENIED,
      ORDER_STATUS.CLAIM_DENIED,
      ORDER_STATUS.RETURN_CANCELLED,
      'partial_shipped',
      'refunded',
      'partial_refund',
      'full_refund',
      'buyer_funded_claim',
      'homitag_funded_claim',
      'seller_funded_claim',
    ],
    options: [
      'View Order Status',
      'Message Buyer',
      'Use Listing as a Template',
      'Help',
      'Cancel',
    ],
  },
  {
    name: 'Return/Cancellation',
    id: 4,
    statuses: [
      ORDER_STATUS.RETURN_CANCELLED,
      ORDER_STATUS.RETURN_ACCEPTED,
      ORDER_STATUS.RETURN_CLOSED,
      ORDER_STATUS.RETURN_COMPLETED,
      ORDER_STATUS.RETURN_REQUESTED,
      ORDER_STATUS.RETURN_SHIPPED,
      ORDER_STATUS.CANCELLATION_REQUESTED,
      ORDER_STATUS.CANCELLED,
      ORDER_STATUS.CLAIM_ACCEPTED,
      ORDER_STATUS.CLAIM_DISPUTED,
      ORDER_STATUS.CLAIM_FILED,
      ORDER_STATUS.CLAIM_CLOSED,
      ORDER_STATUS.RETURN_DENIED,
    ],
    options: [
      'View Order Status',
      'Message Buyer',
      'Use Listing as a Template',
      'Help',
      'Cancel',
    ],
  },
  {
    name: 'Pending Reviews',
    id: 5,
    statuses: [
      ORDER_STATUS.DELIVERED,
      ORDER_STATUS.CLAIM_CLOSED,
      ORDER_STATUS.RETURN_DENIED,
      ORDER_STATUS.RETURN_CANCELLED,
    ],
    options: [
      'View Order Status',
      'Message Buyer',
      'Use Listing as a Template',
      'Help',
      'Cancel',
    ],
  },
];
