import { createImageProgress } from 'react-native-image-progress';
import FastImage from 'react-native-fast-image';
import { ModalPicker, ModalPickerItem } from './ModalPicker';

export { ModalPicker, ModalPickerItem };
export { default as BodyText } from './BodyText';
export { default as Sublabel } from './Sublabel';
export { default as NormalButton } from './NormalButton';
export { default as InputText } from './InputText';
export { default as Currency } from './Currency';
export { default as Picture } from './Picture';
export { SubHeader, Header } from './Header';
export { default as Icon } from './Icon';
export { default as Heading } from './Heading';
export { default as DetailText } from './DetailText';
export { default as Label } from './Label';
export { default as StarsRate } from './StarsRate';
export { default as Button } from './Button';
export { default as Loader } from './Loader';
export { default as LocationInput } from './LocationInput';
export { default as RangeSliderInput } from './RangeSliderInput';
export { default as RadioInputs } from './RadioInputs';
export { default as Tag } from './Tag';
export { default as CategoryTag } from './CategoryTag';
export { default as CustomSelectInput } from './CustomSelectInput';
export { default as TypeTag } from './TypeTag';
export { default as CheckboxesFilterInput } from './CheckboxesFilterInput';
export { default as Tab } from './Tab';
export { default as ProductsList } from './ProductsList';
export { default as EmptyState } from './EmptyState';
export { default as CheckBox } from './CheckBox';
export { default as CheckBoxSquare } from './CheckBoxSquare';
export { default as Divider } from './Divider';
export { default as Link } from './Link';
export { default as StepsBar } from './StepsBar';
export { default as ColorTag } from './ColorTag';
export { default as InputSearchLocation } from './InputSearchLocation';
export { default as ConversationTile } from './ConversationTile';
export { default as FooterAction } from './FooterAction';
export { default as CurrencyInput } from './CurrencyInput';
export { default as SweetAlert } from './SweetAlert';
export { default as SweetDialog } from './SweetDialog';
export { default as SweetCustomAlert } from './SweetCustomAlert';
export { default as FullScreenLoader } from './FullScreenLoader';
export { default as CurrencyInputSell } from './CurrencyInputSell';
export { default as ItemSellObj } from './ItemSellObj';
export { default as ButtonWithTitle } from './ButtonWithTitle';
export { default as CustomDateTimePicker } from './CustomDateTimePicker';
export { default as IconBadge } from './IconBadge';
export { default as CollapsibleText } from './CollapsibleText';
export { default as Toast } from './Toast';
export { default as BoldText } from './BoldText';
export { default as RadioButton } from './RadioButton';

const CachedImage = createImageProgress(FastImage);
export { CachedImage };