import { ORDER_STATUS } from '#utils/enums';

export const orderStatusValue = {
  BUYER: {
    [ORDER_STATUS.ACCEPTED]: 'ACCEPTED',
    [ORDER_STATUS.CREATED]: 'CREATED',
    [ORDER_STATUS.PENDING]: 'PENDING',
    [ORDER_STATUS.PARTIAL_SHIPPED]: 'PARTIAL SHIPPED',
    [ORDER_STATUS.DELIVERED]: 'DELIVERED',
    [ORDER_STATUS.RETURN_CANCELLED]: 'RETURN CANCELLED',
    [ORDER_STATUS.RETURN_DENIED]: 'RETURN DECLINED',
    [ORDER_STATUS.RETURN_RETURNED]: 'RETURN RETURNED',
    [ORDER_STATUS.RETURN_COMPLETED]: 'RETURN COMPLETED',
    [ORDER_STATUS.RETURN_REQUESTED]: 'RETURN REQUESTED',
    [ORDER_STATUS.CANCELLATION_REQUESTED]: 'CANCELLATION REQUESTED',
    [ORDER_STATUS.CANCELLATION_DENIED]: 'ACCEPTED',
    [ORDER_STATUS.CANCELLED]: 'CANCELLED',
    [ORDER_STATUS.AWAITING_SHIPPING]: 'AWAITING SHIPPING',
    [ORDER_STATUS.SHIPPED]: 'SHIPPED',
    [ORDER_STATUS.RETURN_REQUESTED]: 'REQUESTED',
    [ORDER_STATUS.RETURN_DENIED]: 'RETURN DENIED', // UNSURE
    [ORDER_STATUS.IN_TRANSIT]: 'SHIPPED',
    [ORDER_STATUS.RETURN_ACCEPTED]: 'LABEL SHARED',
    [ORDER_STATUS.RETURN_CLOSED]: 'RETURN CLOSED',
    [ORDER_STATUS.CLAIM_FILED]: 'CLAIM FILED',
    [ORDER_STATUS.CLAIM_ACCEPTED]: 'CLAIM GRANTED',
    [ORDER_STATUS.CLAIM_DISPUTED]: 'CLAIM DISPUTED',
    [ORDER_STATUS.CLAIM_CLOSED]: 'CLAIM CLOSED',
    [ORDER_STATUS.RETURN_SHIPPED]: 'RETURN SHIPPED'
  },
  SELLER: {
    [ORDER_STATUS.ACCEPTED]: 'AWAITING SHIPMENT',
    [ORDER_STATUS.CREATED]: 'CREATED',
    [ORDER_STATUS.PENDING]: 'PENDING',
    [ORDER_STATUS.DELIVERED]: 'DELIVERED',
    [ORDER_STATUS.RETURN_CANCELLED]: 'RETURN CANCELLED',
    [ORDER_STATUS.RETURN_DENIED]: 'RETURN DECLINED',
    [ORDER_STATUS.RETURN_RETURNED]: 'RETURN RETURNED',
    [ORDER_STATUS.RETURN_COMPLETED]: 'RETURN COMPLETED',
    [ORDER_STATUS.RETURN_REQUESTED]: 'RETURN REQUESTED',
    [ORDER_STATUS.CANCELLATION_REQUESTED]: 'CANCELLATION REQUESTED',
    [ORDER_STATUS.CANCELLATION_DENIED]: 'AWAITING SHIPMENT',
    [ORDER_STATUS.CANCELLED]: 'CANCELLED',
    [ORDER_STATUS.AWAITING_SHIPPING]: 'AWAITING SHIPPING',
    [ORDER_STATUS.SHIPPED]: 'SHIPPED',
    [ORDER_STATUS.IN_TRANSIT]: 'SHIPPED',
    [ORDER_STATUS.RETURN_ACCEPTED]: 'LABEL SHARED',
    [ORDER_STATUS.RETURN_CLOSED]: 'RETURN CLOSED',
    [ORDER_STATUS.CLAIM_FILED]: 'CLAIM FILED',
    [ORDER_STATUS.CLAIM_ACCEPTED]: 'CLAIM GRANTED',
    [ORDER_STATUS.CLAIM_DISPUTED]: 'CLAIM DISPUTED',
    [ORDER_STATUS.CLAIM_CLOSED]: 'CLAIM CLOSED',
    [ORDER_STATUS.RETURN_SHIPPED]: 'RETURN SHIPPED'
  },
};

export const orderStatusText = {
  [ORDER_STATUS.ACCEPTED]: 'Order Status ',
  [ORDER_STATUS.CREATED]: 'Order Status ',
  [ORDER_STATUS.PENDING]: 'Order Status ',
  [ORDER_STATUS.DELIVERED]: 'Order Status ',
  [ORDER_STATUS.PARTIAL_SHIPPED]: 'Order Status ',
  [ORDER_STATUS.RETURN_CLOSED]: 'Order Status ',
  [ORDER_STATUS.RETURN_DENIED]: 'Order Status ',
  [ORDER_STATUS.RETURN_CANCELLED]: 'Return Status ',

  [ORDER_STATUS.RETURN_RETURNED]: 'Return Status ',
  [ORDER_STATUS.RETURN_COMPLETED]: 'Return Status ',
  [ORDER_STATUS.RETURN_REQUESTED]: 'Return Status ',
  [ORDER_STATUS.CANCELLATION_REQUESTED]: 'Order Status ',
  [ORDER_STATUS.CANCELLED]: 'Order Status ',
  [ORDER_STATUS.AWAITING_SHIPPING]: 'Order Status ',
  [ORDER_STATUS.CANCELLATION_DENIED]: 'Order Status ',
  [ORDER_STATUS.SHIPPED]: 'Order Status ',
  [ORDER_STATUS.RETURN_REQUESTED]: 'Return Status ',
  [ORDER_STATUS.RETURN_DENIED]: 'Return Status ',
  [ORDER_STATUS.CLAIM_FILED]: 'Claim Status ',
  [ORDER_STATUS.IN_TRANSIT]: 'Order Status ',
  [ORDER_STATUS.RETURN_ACCEPTED]: 'Return Status ',
  [ORDER_STATUS.RETURN_CLOSED]: 'Return Status ',
  [ORDER_STATUS.RETURN_SHIPPED]: 'Return Status ',
  [ORDER_STATUS.CLAIM_ACCEPTED]: 'Claim Status ',
  [ORDER_STATUS.CLAIM_DISPUTED]: 'Claim Status ',
  [ORDER_STATUS.CLAIM_CLOSED]: 'Claim Status ',
};

export const MORE_BUTTON_BUYER = {
  [ORDER_STATUS.CREATED]: ['Cancel'],
  [ORDER_STATUS.PENDING]: ['Cancel'],
  [ORDER_STATUS.ACCEPTED]: ['Request to Cancel', 'Cancel'],
  [ORDER_STATUS.CANCELLATION_REQUESTED]: ['Cancel'],
  [ORDER_STATUS.CANCELLED]: ['Cancel'],
  [ORDER_STATUS.CANCELLATION_DENIED]: ['Cancel'],
  [ORDER_STATUS.SHIPPED]: ['Cancel'],
  [ORDER_STATUS.RETURN_RETURNED]: ['View Order Details', 'Cancel'],
  [ORDER_STATUS.RETURN_COMPLETED]: ['View Order Details', 'Cancel'],
  [ORDER_STATUS.PARTIAL_SHIPPED]: ['Request to Cancel', 'Cancel'], // only supplier order possible
  [ORDER_STATUS.DELIVERED]: ['Cancel'], // also depends on availableClaim ,
  [ORDER_STATUS.RETURN_CANCELLED]: ['Cancel'], // also depends on availableClaim ,

  [ORDER_STATUS.RETURN_REQUESTED]: [
    'View Order Details',
    'Cancel Return',
    'Cancel',
  ],
  [ORDER_STATUS.RETURN_ACCEPTED]: [
    'View Order Details',
    'Cancel',
  ],
  [ORDER_STATUS.RETURN_DENIED]: ['View Order Details', 'Cancel'],
  [ORDER_STATUS.RETURN_CLOSED]: ['View Order Details', 'Cancel'],
  [ORDER_STATUS.CLAIM_FILED]: ['View Order Details', 'Cancel Claim', 'Cancel'],
  [ORDER_STATUS.CLAIM_ACCEPTED]: ['View Order Details', 'Cancel'],
  [ORDER_STATUS.CLAIM_DISPUTED]: [
    'View Order Details',
    'Cancel Claim',
    'Cancel',
  ],
  [ORDER_STATUS.PARTIAL_SHIPPED]: ['Cancel'],
  [ORDER_STATUS.CLAIM_CLOSED]: ['View Order Details', 'Cancel'],
  [ORDER_STATUS.AWAITING_SHIPPING]: ['Request to Cancel', 'Cancel'],
  [ORDER_STATUS.IN_TRANSIT]: ['Cancel'],
  [ORDER_STATUS.RETURN_SHIPPED]: ['View Order Details', 'Cancel'],
};

export const MORE_BUTTON_SELLER = {
  [ORDER_STATUS.CREATED]: ['Cancel'],
  [ORDER_STATUS.PENDING]: ['Cancel'],
  [ORDER_STATUS.ACCEPTED]: ['Cancel Order', 'Cancel'],
  [ORDER_STATUS.CANCELLATION_REQUESTED]: ['Cancel Order', 'Cancel'],
  [ORDER_STATUS.CANCELLED]: ['Cancel'],
  // [ORDER_STATUS.CANCELLED]: ['Repost Item', 'Cancel'],
  [ORDER_STATUS.CANCELLATION_DENIED]: ['Cancel Order', 'Cancel'],
  [ORDER_STATUS.SHIPPED]: ['Issue Refund', 'Cancel'],
  [ORDER_STATUS.DELIVERED]: ['Issue Refund', 'Cancel'],
  [ORDER_STATUS.RETURN_REQUESTED]: ['View Order Details','Issue Refund', 'Cancel'],
  [ORDER_STATUS.RETURN_CANCELLED]: ['View Order Details','Issue Refund', 'Cancel'],

  [ORDER_STATUS.RETURN_ACCEPTED]: [
    'View Order Details',
    'Resend Label',
    'Close Return',
    'Issue Refund',
    'Cancel',
  ],
  [ORDER_STATUS.RETURN_DENIED]: [
    'Issue Refund',
    'View Order Details',
    'Close Return',
    'Cancel',
  ],
  [ORDER_STATUS.RETURN_RETURNED]: [
    'View Order Details',
    'Issue Refund',
    'Close Return',
    'Cancel',
  ],
  [ORDER_STATUS.RETURN_COMPLETED]: [
    'View Order Details',
    'Issue Refund',
    'Close Return',
    'Cancel',
  ],
  [ORDER_STATUS.RETURN_CLOSED]: ['Issue Refund', 'View Receipt', 'Cancel'],
  [ORDER_STATUS.CLAIM_FILED]: ['Issue Refund', 'View Order Details', 'Cancel'],
  [ORDER_STATUS.CLAIM_ACCEPTED]: [
    'View Order Details',
    'Issue Refund',
    'Cancel',
  ],
  [ORDER_STATUS.CLAIM_DISPUTED]: [
    'View Order Details',
    'Issue Refund',
    'Cancel',
  ],
  [ORDER_STATUS.CLAIM_CLOSED]: ['View Order Details', 'Issue Refund', 'Cancel'],
  [ORDER_STATUS.AWAITING_SHIPPING]: ['Cancel Order', 'Cancel'],
  [ORDER_STATUS.IN_TRANSIT]: ['Cancel'],
  [ORDER_STATUS.RETURN_CLOSED]: [
    'Issue Refund',
    'View Order Details',
    'Cancel',
  ],
  [ORDER_STATUS.RETURN_SHIPPED]: [
    'Issue Refund',
    'View Order Details',
    'Cancel',
  ],
};
