import { StyleSheet } from 'react-native';
import { Metrics, Colors, Fonts } from '#themes';

export const styles = StyleSheet.create({
  MainContainer: {
    flex: 1,
  },
  Container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  rightIcon: {
    paddingRight: 15,
  },
  headerContainer: {
    flex: 0.7,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerImg: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    borderRadius: 5,
    overflow: 'hidden',
    marginRight: 15,
  },
  headerTextContainer: {
    flex: 1,
    flexDirection: 'column',
  },
  headerTitleText: {
    fontFamily: Fonts.family.regular,
    color: '#313334',
    fontWeight: '600',
    fontSize: 18,
    textAlign: 'left',
    marginBottom: 5,
  },
  headerSubTitleText: {
    fontFamily: Fonts.family.regular,
    color: '#696969',
    fontWeight: '600',
    fontSize: 10,
    textAlign: 'left',
  },
  msgSendContainer: {
    flexDirection: 'column',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 24,
    zIndex: 3,
    backgroundColor: '#FFF',
  },
  msgHintsContainer: {
    height: 68,
    flexDirection: 'row',
    paddingTop: 15,
  },
  msgHintsContainerNoTop: {
    height: 20,
    flexDirection: 'row',
    paddingTop: 15,
  },
  msgHintsContainerOffer: {
    height: 90,
    flexDirection: 'column',
    paddingTop: 10,
  },
  offerActionsContainer: {
    flexDirection: 'column',
    width: '100%',
  },
  msgBoxContainer: {
    flexDirection: 'row',
    marginHorizontal: 20,
    alignItems: 'flex-end',
    marginBottom: 20,
  },
  msgTextContainer: {
    marginRight: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 24,
    backgroundColor: '#fff',
    borderRadius: 24,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flex: 1,
  },
  textInput: {
    fontFamily: Fonts.family.regular,
    color: '#969696',
    fontWeight: 'normal',
    fontSize: 13,
    padding: 0,
  },
  msgSendButton: {
    width: 49,
    height: 49,
    backgroundColor: '#7471FF',
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hintButton: {
    height: 38,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7471FF',
    borderRadius: 7,
    marginLeft: 20,
  },
  textHintButton: {
    fontFamily: Fonts.family.regular,
    fontWeight: '500',
    fontSize: 13,
    color: '#fff',
  },
  bubbleTimeText: {
    fontFamily: Fonts.family.regular,
    fontWeight: 'normal',
    fontSize: 10,
    color: '#313334',
    textAlign: 'right',
    marginTop: 5,
  },
  bubbleMsgText: {
    fontFamily: Fonts.family.regular,
    fontWeight: 'normal',
    fontSize: 13,
    color: '#313334',
  },
  ChatListContainer: {
    paddingHorizontal: 20,
  },
  mineBubbleContainer: {
    backgroundColor: '#F5F5F5',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 10,
    alignSelf: 'flex-end',
    flexShrink: 1,
    marginLeft: 60,
  },
  externalBubbleContainer: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    alignSelf: 'flex-start',
    flexShrink: 1,
    backgroundColor: '#FFF',
    borderRadius: 14,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    marginRight: 40,
  },
  externalImg: {
    width: 34,
    height: 34,
    resizeMode: 'contain',
    borderRadius: 17,
    overflow: 'hidden',
    marginRight: 15,
  },
  externalContainer: {
    flex: 1,
    flexDirection: 'row',
    marginVertical: 5,
  },
  mineContainer: {
    flex: 1,
    alignItems: 'flex-end',
    marginVertical: 5,
  },
  headerTitle: {
    width: 'auto',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF',
    marginVertical: 20,
    padding: 5,
    alignSelf: 'center',
    borderRadius: 10,
  },
  headerText: {
    fontFamily: Fonts.family.regular,
    fontWeight: 'normal',
    fontSize: 10,
    color: '#969696',
  },
  offerOptionsContainer: {
    flexDirection: 'row',
    width: '100%',
    paddingHorizontal: 15,
  },
  hintButtonOffer: {
    height: 38,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7471FF',
    borderRadius: 7,
    marginVertical: 5,
    flex: 1,
    marginHorizontal: 5,
  },
  offerTextContainer: {
    width: '100%',
    paddingHorizontal: 20,
    paddingTop: 5,
  },
  mapContainer: {
    width: '100%',
    height: 214,
  },
  mapToTap: {
    width: '100%',
    height: 214,
    backgroundColor: 'transparent',
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 2,
  },
  offerStatusContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  offerStatusText: {
    fontFamily: Fonts.family.regular,
    fontWeight: 'normal',
    fontSize: 10,
    color: '#313334',
    lineHeight: 12,
    marginHorizontal: 6,
    textTransform: 'uppercase',
  },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: '#969696',
  },
  actionSheetButtonText: {
    color: '#313334',
    fontFamily: Fonts.family.semiBold,
    fontSize: 13,
  },
  cancelButtonBox: {
    backgroundColor: '#FF5556',
  },
});
