import { StyleSheet } from 'react-native';
import { Colors, Fonts, Metrics } from '#themes';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  descriptionText: {
    ...Fonts.style.homiBodyText,
    color: Colors.black,
    textAlign: 'center',
    marginHorizontal: 20,
    marginTop: 20,
  },
  mainContainer1: {
    height: 100,
    backgroundColor: Colors.backgroundGrey,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  takePhotoBtnContainer: {
    height: 45,
    width: (Metrics.width / 3) * 2,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: Colors.active,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraIcon: {
    width: 25,
    height: 25,
    resizeMode: 'contain',
    marginRight: 10,
  },
  blackText: {
    color: Colors.black,
    fontSize: Fonts.size.medium,
    lineHeight: 22,
    fontFamily: Fonts.family.medium,
  },
  activeText: {
    color: Colors.active,
    fontSize: Fonts.size.medium,
    lineHeight: 16,
    fontFamily: Fonts.family.semiBold,
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  mainContainer2: {
    marginTop: 40,
    alignItems: 'center',
  },
  photoImg: {
    width: Metrics.height / 4,
    height: Metrics.height / 4,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: 30,
  },
  bottomBtnContainer: {
    height: 100,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowRadius: 3,
    shadowOpacity: 0.1,
    elevation: 4,
  },
  scrollConatiner: {
    marginBottom: 130,
  },
  dotsContainer: {
    height: 10,
    position: 'absolute',
    bottom: 110,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  dot1: {
    width: 8,
    height: 8,
    borderRadius: 3,
    backgroundColor: Colors.active,
    marginRight: 3,
  },
  dot2: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.inactiveShape,
    marginLeft: 3,
  },
});
