export const SET_CHAT_DATA = 'SET_CHAT_DATA';
export const RECEIVE_CHAT_MSG = 'RECEIVE_CHAT_MSG';
export const CLEAR_CHAT = 'CLEAR_CHAT';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_CONVERSATIONS = 'RECEIVE_CONVERSATIONS';
export const GET_CHAT_DATA = 'GET_CHAT_DATA';
export const CLEAR_BADGE = 'CLEAR_BADGE';
export const SEEN_CONVERSATION = 'SEEN_CONVERSATION';
export const UPDATE_CONVERSATION_VISIBILITY = 'UPDATE_CONVERSATION_VISIBILITY';
/* Store Key */
export const CHAT = 'chat';
