platform :ios, '12.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

install! 'cocoapods', :deterministic_uuids => false

target 'homitag' do
 use_modular_headers!
  config = use_native_modules!

  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency.podspec"
  # pod 'Firebase/Auth'
  # pod 'AppAuth', '~> 1.2.0'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  # pod 'Firebase/Analytics'
  pod 'BoringSSL-GRPC', '= 0.0.24', :modular_headers => false
  pod 'gRPC-Core', '= 1.44.0', :modular_headers => false
  use_native_modules!

  # pod 'RNSha1', :path => '../node_modules/react-native-sha1'
  pod 'GoogleSignIn', '~> 7.0'
  pod 'Stripe', '>= 21.3.1'
  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
