import fonts from '#themes/fonts';
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  dash_container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
  },
  shippingInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 30,
    marginBottom: 15,
    marginHorizontal: 20,
  },
  orderStatusText: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowItemsContainer: {
    paddingHorizontal: 20,
  },
  footerInfo: {
    fontFamily: fonts.family.Regular,
    fontSize: 15,
    marginBottom: 20,
    marginTop: 10,
  },
  mainContainer: { flex: 1, justifyContent: 'space-between' },
  mainHeader: {
    elevation: 3,
    backgroundColor: '#ffffff',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 15,
    flexDirection: 'row',
  },
  mainHeaderTxt: { fontFamily: fonts.family.semiBold, fontSize: 16, marginLeft: 30 },
  viewOrderTxt: {
    fontFamily: fonts.family.semiBold,
    fontSize: 10,
    marginBottom: 15,
    textDecorationLine: 'underline',
    textAlign: 'center',
  },
  sepLine: {
    width: '90%',
    height: 1,
    backgroundColor: '#76767630',
    alignSelf: 'center',
    marginBottom: 20,
  },
  sepLine2: {
    width: '90%',
    height: 1,
    backgroundColor: '#76767630',
    alignSelf: 'center',
    marginTop: 30,
    marginBottom: 20,
  },
  denyTxt: {
    fontFamily: fonts.family.semiBold,
    fontSize: 15,
    textAlign: 'left',
    marginTop: 20,
    marginLeft: 20,
  },
  commentInput: {
    fontFamily: fonts.family.semiBold,
    fontSize: 16,
    marginHorizontal: 20,
    padding: 0,
    borderBottomColor: '#96969660',
    borderBottomWidth: 1,
  },
  cancellationRespond: {
    fontFamily: fonts.family.regular,
    fontSize: 14,
    textAlign: 'center',
  },
  cancellationDetailsTxt: {
    fontFamily: fonts.family.semiBold,
    fontSize: 15,
    textAlign: 'left',
    marginVertical: 20,
    marginLeft: 20,
  },
  cancellationDetailContainer: {
    backgroundColor: '#F5F5F5',
    padding: 10,
    paddingVertical: 15,
  },
  commentBox: {
    fontFamily: fonts.family.regular,
    fontSize: 14,
    paddingBottom: 8,
    marginHorizontal: 27.5,
    textAlign: 'center',
    color: '#767676',
  },
  waysToRespTxt: {
    fontFamily: fonts.family.semiBold,
    fontSize: 15,
    textAlign: 'left',
    marginVertical: 15,
    marginLeft: 20,
  },
  waysToRespBox: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
    marginHorizontal: 10,
  },
  contentItemConainer: {
    flex: 1,
    height: 220,
    borderRadius: 8,
    flexDirection: 'column',
    margin: 7.5,
    backgroundColor: 'white',
    elevation: 6,
  },
  contentItemHeader: {
    paddingVertical: 12,
    backgroundColor: '#00BDAA',
    borderTopRightRadius: 8,
    borderTopLeftRadius: 8,
  },
  itemHeaderText: {
    fontFamily: fonts.family.medium,
    fontSize: 13,
    color: '#FFF',
    textAlign: 'center',
    fontWeight: '600',
  },
  contentIconContainer: {
    paddingVertical: 15,
    alignItems: 'center',
  },
  itemDetailText: {
    fontFamily: fonts.family.Regular,
    fontSize: 13,
    color: '#969696',
    fontWeight: '500',
    lineHeight: 18,
    textAlign: 'center',
  },
  itemDetailContainer: {
    paddingHorizontal: 10,
  },
});
