export const GET_SUPPLIER_DATA = 'GET_SUPPLIER_DATA';
export const GET_SUPPLIER_PRODUCT_LIST = 'GET_SUPPLIER_PRODUCT_LIST';
export const GET_NEXT_SUPPLIER_PRODUCT_LIST = 'GET_NEXT_SUPPLIER_PRODUCT_LIST';
export const GET_CATALOG_LIST = 'GET_CATALOG_LIST';
export const GET_PRODUCTS_PER_CATALOG = 'GET_PRODUCTS_PER_CATALOG';

export const UPDATE_PRODUCTS_PER_CATALOG = 'UPDATE_PRODUCTS_PER_CATALOG';

/* Store reducer key */
export const CATALOG = 'catalog';
