export const PERSIST_FILTER_VALUES = 'PERSIST_FILTER_VALUES';
export const SET_PROPERTIES = 'SET_PROPERTIES';
export const PERSIST_PROPERTIES_VALUES = 'PERSIST_PROPERTIES_VALUES';
export const SET_PROPERTIES_VALUES = 'SET_PROPERTIES_VALUES';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const GET_SEARCH_TEXT_SUGGESTIONS = 'GET_SEARCH_TEXT_SUGGESTIONS';
export const GET_MAX_PRICE_PER_CATEGORY = 'GET_MAX_PRICE_PER_CATEGORY';
export const GET_CUSTOM_FILTER_OPTIONS_LIST = 'GET_CUSTOM_FILTER_OPTIONS_LIST';
export const RESET_FILTERS_TO_DEFAULT = 'RESET_FILTERS_TO_DEFAULT';
export const GET_MODELS_BY_MAKE = 'GET_MODELS_BY_MAKE';
export const PERSIST_LOCATION_SEARCH_PRE_VALUES = 'PERSIST_LOCATION_SEARCH_PRE_VALUES';

/* Store Key */
export const FILTERS = 'FILTERS';
